<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PU8VKKP8" failures="1" tests="3" name="Ecommerce Error Validation Test Cases" time="15.911" errors="0" timestamp="2022-11-29T14:32:00 IST">
  <testcase classname="EcommerceErrorCheckTestCases.SignupPageErrorMessgeValidation1" name="@AfterTest tearDown" time="0.092">
    <failure type="org.openqa.selenium.NoSuchSessionException" message="invalid session id
Build info: version: &amp;apos;4.4.0&amp;apos;, revision: &amp;apos;e5c75ed026a&amp;apos;
System info: host: &amp;apos;LAPTOP-PU8VKKP8&amp;apos;, ip: &amp;apos;192.168.1.4&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.2&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [cefd1e8a81474f282180bbb881478bd3, close {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.121, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\JINTO\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:3964}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:3964/devtool..., se:cdpVersion: 107.0.5304.121, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: cefd1e8a81474f282180bbb881478bd3">
      <![CDATA[org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'LAPTOP-PU8VKKP8', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [cefd1e8a81474f282180bbb881478bd3, close {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.121, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\JINTO\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:3964}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:3964/devtool..., se:cdpVersion: 107.0.5304.121, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: cefd1e8a81474f282180bbb881478bd3
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:432)
at EcommerceErrorCheckTestCases.SignupPageErrorMessgeValidation1.tearDown(SignupPageErrorMessgeValidation1.java:41)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="EcommerceErrorCheckTestCases.SignupPageErrorMessgeValidation2" name="@AfterTest tearDown" time="-1.669712520796E9">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="EcommerceErrorCheckTestCases.SignupPageErrorMessgeValidation1" name="SignUpCheck" time="0.771"/>
  <testcase classname="EcommerceErrorCheckTestCases.SignupPageErrorMessgeValidation2" name="SignUpCheck" time="0.672">
    <failure type="java.lang.AssertionError" message="expected [JINTOLKJHGFDGHJKYLHGFGFDHJFGHJDFGJDFGHJFGHJGHJGHJGFJFGHJFGHFGHJFGHJFGHJFGGHJFGJFGHJFGHJGFHJHGFJGFHJ] but found [SIGN UP]">
      <![CDATA[java.lang.AssertionError: expected [JINTOLKJHGFDGHJKYLHGFGFDHJFGHJDFGJDFGHJFGHJGHJGHJGFJFGHJFGHFGHJFGHJFGHJFGGHJFGJFGHJFGHJGFHJHGFJGFHJ] but found [SIGN UP]
at EcommerceErrorCheckTestCases.SignupPageErrorMessgeValidation2.SignUpCheck(SignupPageErrorMessgeValidation2.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SignUpCheck -->
  <testcase classname="EcommerceErrorCheckTestCases.SignInPageErrorMsgValidation" name="signInCheck" time="0.743"/>
</testsuite> <!-- Ecommerce Error Validation Test Cases -->
